# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    build:
      context: mongodb
      dockerfile: Dockerfile
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/db:/data/db
      - ./mongodb/configdb:/data/configdb

  node:
    image: node:latest
    restart: always
    ports:
      - 9999:3000
    volumes:
      - ./src:/src
    working_dir: /src
    command: bash -c "npm i && npm run dev"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example