# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb

  node:
    image: node:latest
    restart: always
    ports:
      - 9999:3000
    volumes:
      - ./src:/src
    working_dir: /src
    command: bash -c "npm i && npm run start"
