openapi: 3.0.0
info:
  title: backend
  version: '2.0'
  contact:
    name: masuda yasuto
    url: 'https://boxlister.ciebus.net/'
  description: boxlister backend
servers:
  - url: 'http://localhost:3000/api/v2'
paths:
  /box:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-box
  '/box/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    post:
      summary: ''
      operationId: post-box-id
      responses:
        '200':
          description: OK
  /box/new:
    post:
      summary: ''
      operationId: post-box-new
      responses:
        '200':
          description: OK
components:
  schemas: {}
  securitySchemes:
    Token:
      name: API Key
      type: apiKey
      in: header
